
1. https://codeforces.com/contest/1326/problem/D2 ( manchar + advance string algorithms + two pointer)
2. https://codingcompetitions.withgoogle.com/kickstart/round/000000000019ffc7/00000000001d40bb (dp)
3. https://codeforces.com/contest/1312/problem/E (dp)
4. https://codeforces.com/contest/1327/problem/D (maths + divisors + cycle length + graph logic)
5. https://codeforces.com/contest/1323/problem/D (bitmask + maths + bit logic + sum pair in given range)
6. https://codeforces.com/contest/1187/problem/E (rooting technique)
7. https://codeforces.com/contest/1316/problem/E (dp + bitmask + greedy)
8. https://leetcode.com/problems/count-of-range-sum/ (bit , divide & conqure) (a[i]+l<=a[j]<=a[i]+r,i<j)
9. https://leetcode.com/contest/weekly-contest-182/problems/find-all-good-strings/ ( digit dp + kmp + substring matching)
10.https://atcoder.jp/contests/abc152/tasks/abc152_e (lcm + prime_factorization)
11.https://codeforces.com/gym/102556/problem/H (gcf + prime_factorization + conribution of factor)
12.https://atcoder.jp/contests/abc162/tasks/abc162_f (dp)
13.https://atcoder.jp/contests/abc163/tasks/abc163_e (dp)
14.https://codeforces.com/contest/791/problem/D (treedp + dfs + all pair path sum)
15.https://www.codechef.com/problems/PRTTME/ ( inclusion-exclusion  + maths)
16.https://codeforces.com/contest/1342/problem/E (inclusion - exclusion  + combinatorics)
17.https://atcoder.jp/contests/abc152/tasks/abc152_f (inclusion-exclusion + tree + bitmasking + maths)
18.https://www.codechef.com/problems/DGTCNT (classical digit dp + inclusion-exclusion)
19.https://atcoder.jp/contests/abc165/tasks/abc165_f (lis on tree + dp + dfs)
20.https://www.hackerrank.com/contests/codeagon/challenges/number-of-ways-1 ( dp + dp + dp )
21.https://atcoder.jp/contests/abc168/tasks/abc168_e (maths + hashing)
22.https://leetcode.com/contest/weekly-contest-189/problems/maximum-number-of-darts-inside-of-a-circular-dartboard/ (geometry)
23.https://codeforces.com/contest/1354/problem/C2 (geometry + math)
24.https://codeforces.com/contest/612/problem/E (square root permutation)
25.https://codeforces.com/contest/817/problem/D
26.https://codeforces.com/contest/1364/problem/D (cycle in graph)
27.https://www.codechef.com/problems/ABSNX/ (bit,stack,min - max)
25.https://atcoder.jp/contests/abc130/tasks/abc130_e(dp + optimization)
26.https://atcoder.jp/contests/abc133/tasks/abc133_f(tree + segment tree)
27.https://atcoder.jp/contests/abc138/tasks/abc138_f (dp , y - x = y ^ x , L <= x <= y <= R)
28.https://atcoder.jp/contests/m-solutions2019/tasks/m_solutions2019_e (Product of N terms of Ap)